apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: superstudentdiscountapi
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
    rules:
        - http:
            paths:
            - path: /service
              backend:
                serviceName: superstudentdiscountapi
                servicePort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: superstudentdiscountapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: superstudentdiscountapi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: superstudentdiscountapi
spec:
  selector:
    matchLabels:
      app: superstudentdiscountapi
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: superstudentdiscountapi
    spec:
      containers:
      - name: superstudentdiscountapi
        image: dnunley/superstudentdiscountapi:{buildId}
        ports:
        - containerPort: 80